name: Aditus
description: Getting words for project names
version: 0.0.1
homepage: https://github.com/Ampless/Aditus

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
