name: Adimus
description: Getting words for project names
version: 0.1.1
homepage: https://github.com/Ampless/Aditus

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  html_search: ^0.2.0
  schttp: ^3.2.0

dev_dependencies:
  pedantic: ^1.11.0
