name: adimus
description: Getting words for project names
version: 0.2.1
homepage: https://github.com/Ampless/Adimus

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  fhir_yaml: ^0.4.0
  html: ^0.15.0
  html_search: ^0.3.0
  http: ^0.13.5
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
